<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="MAIN" Id="{2a11b0b8-4c62-4315-92a5-302ee14477bd}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	sTypeName : T_MaxString;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[sTypeName := F_GetVariablePath(sTypeName);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>