<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="F_GetDateArrayUpperBound" Id="{3209aba7-e7e1-0c97-0970-b761fd621058}" SpecialFunc="None">
    <Declaration><![CDATA[// Gets the upper bound index of the array of specified type.
FUNCTION F_GetDateArrayUpperBound : T_Position // The upper bound index of the specified array.
VAR_IN_OUT
	arArray : ARRAY[*] OF DATE; // The array to query.
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_GetDateArrayUpperBound := UPPER_BOUND(arArray, 1);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>