<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="F_GetBoolArrayLowerBound" Id="{2dd79da3-c3d0-0aa6-39a2-e1f0dbec617e}" SpecialFunc="None">
    <Declaration><![CDATA[// Gets the lower bound index of the array of specified type.
FUNCTION F_GetBoolArrayLowerBound : T_Position // The lower bound index of the specified array.
VAR_IN_OUT
	arArray : ARRAY[*] OF BOOL; // The array to query.
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_GetBoolArrayLowerBound := LOWER_BOUND(arArray, 1);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>