<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="F_GetLRealArrayUpperBound" Id="{61c00104-d01e-089b-31a5-d0c2c667c48c}" SpecialFunc="None">
    <Declaration><![CDATA[// Gets the upper bound index of the array of specified type.
FUNCTION F_GetLRealArrayUpperBound : T_Position // The upper bound index of the specified array.
VAR_IN_OUT
	arArray : ARRAY[*] OF LREAL; // The array to query.
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_GetLRealArrayUpperBound := UPPER_BOUND(arArray, 1);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>