<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="F_GetPointerArrayUpperBound" Id="{ce1c902d-f22d-07c3-0998-2d54ac6ac38e}" SpecialFunc="None">
    <Declaration><![CDATA[// Gets the upper bound index of the array of specified type.
FUNCTION F_GetPointerArrayUpperBound : T_Position // The upper bound index of the specified array.
VAR_IN_OUT
	arArray : ARRAY[*] OF POINTER TO BYTE; // The array to query.
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_GetPointerArrayUpperBound := UPPER_BOUND(arArray, 1);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>