<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="F_GetPointerArrayLowerBound" Id="{9243c784-9013-04ca-19a7-fdf402536b9f}" SpecialFunc="None">
    <Declaration><![CDATA[// Gets the lower bound index of the array of specified type.
FUNCTION F_GetPointerArrayLowerBound : T_Position // The lower bound index of the specified array.
VAR_IN_OUT
	arArray : ARRAY[*] OF POINTER TO BYTE; // The array to query.
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_GetPointerArrayLowerBound := LOWER_BOUND(arArray, 1);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>