<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="F_GetUSIntArrayLowerBound" Id="{0ec2c87c-59b1-022a-009e-96d1ee7fcd29}" SpecialFunc="None">
    <Declaration><![CDATA[// Gets the lower bound index of the array of specified type.
FUNCTION F_GetUSIntArrayLowerBound : T_Position // The lower bound index of the specified array.
VAR_IN_OUT
	arArray : ARRAY[*] OF USINT; // The array to query.
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_GetUSIntArrayLowerBound := LOWER_BOUND(arArray, 1);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>