<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="F_GetUXIntArrayLowerBound" Id="{213ad537-4ad4-0a69-1c96-30a54f20b2ce}" SpecialFunc="None">
    <Declaration><![CDATA[// Gets the lower bound index of the array of specified type.
FUNCTION F_GetUXIntArrayLowerBound : T_Position // The lower bound index of the specified array.
VAR_IN_OUT
	arArray : ARRAY[*] OF __UXINT; // The array to query.
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_GetUXIntArrayLowerBound := LOWER_BOUND(arArray, 1);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>