<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="F_GetUSIntArrayUpperBound" Id="{bc5e541b-8593-0c77-08cf-595bca411aed}" SpecialFunc="None">
    <Declaration><![CDATA[// Gets the upper bound index of the array of specified type.
FUNCTION F_GetUSIntArrayUpperBound : T_Position // The upper bound index of the specified array.
VAR_IN_OUT
	arArray : ARRAY[*] OF USINT; // The array to query.
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_GetUSIntArrayUpperBound := UPPER_BOUND(arArray, 1);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>