<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="F_GetByteArrayLowerBound" Id="{6d17d8bf-c983-0003-23e7-e114959a1700}" SpecialFunc="None">
    <Declaration><![CDATA[// Gets the lower bound index of the array of specified type.
FUNCTION F_GetByteArrayLowerBound : T_Position // The lower bound index of the specified array.
VAR_IN_OUT
	arArray : ARRAY[*] OF BYTE; // The array to query.
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_GetByteArrayLowerBound := LOWER_BOUND(arArray, 1);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>