<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="F_GetLIntArrayUpperBound" Id="{f2a0f7a9-5c52-0e40-0962-62d1a96230e8}" SpecialFunc="None">
    <Declaration><![CDATA[// Gets the upper bound index of the array of specified type.
FUNCTION F_GetLIntArrayUpperBound : T_Position // The upper bound index of the specified array.
VAR_IN_OUT
	arArray : ARRAY[*] OF LINT; // The array to query.
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_GetLIntArrayUpperBound := UPPER_BOUND(arArray, 1);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>